# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

resources:
- repo: self

variables:
   # Update Azure.ResourceGroupName value with Azure resource group name.
  Azure.ResourceGroupName: 'digital-icebreakers'

  # Update Azure.ServiceConnectionId value with AzureRm service endpoint.
  Azure.ServiceConnectionId: 'digital-icebreakers-service-connection'

  # Update Azure.Location value with Azure Location.
  Azure.Location: 'australiaeast'

  # Update ACR.Name value with ACR name. Please note ACR names should be all lower-case and alphanumeric only.
  ACR.Name: 'stafford'

  ACR.ImageName: 'digitalicebreakers:$(Build.BuildId)'
  ACR.FullName: '$(ACR.Name).azurecr.io'
  Azure.CreateResources: 'true' # Update Azure.CreateResources to false if you have already created resources like resource group and azure container registry.
  System.Debug: 'false'
  version: $(Build.BuildNumber)

jobs:
- job: BuildImage
  displayName: Build
#  dependsOn: CreateResources
#  condition: or(succeeded(), ne(variables['Azure.CreateResources'], 'true'))

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: FileTransform@1
    displayName: 'File Transform: version.json'
    inputs:
      folderPath: $(System.DefaultWorkingDirectory)/DigitalIcebreakers/ClientApp/src
      fileType: json
      targetFiles: 'version.json'
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      azureSubscriptionEndpoint: '$(Azure.ServiceConnectionId)'
      azureContainerRegistry: '$(ACR.FullName)'
      imageName: '$(ACR.ImageName)'
      command: build
      dockerFile: '**/Dockerfile'
  - task: Docker@1
    displayName: Tag $(version)
    inputs:
      command: tag
      imageName: $(ACR.FullName)/$(ACR.ImageName)
      arguments: $(ACR.FullName)/digitalicebreakers:$(version)
  - task: Docker@1
    displayName: Tag latest
    inputs:
      command: tag
      imageName: $(ACR.FullName)/$(ACR.ImageName)
      arguments: $(ACR.FullName)/digitalicebreakers:latest
  - task: Docker@1
    displayName: 'Push $(version)'
    inputs:
      azureSubscriptionEndpoint: '$(Azure.ServiceConnectionId)'
      azureContainerRegistry: '$(ACR.FullName)'
      imageName: $(ACR.FullName)/digitalicebreakers:$(version)
      command: push
  - task: Docker@1
    displayName: 'Push latest'
    inputs:
      azureSubscriptionEndpoint: '$(Azure.ServiceConnectionId)'
      azureContainerRegistry: '$(ACR.FullName)'
      imageName: $(ACR.FullName)/digitalicebreakers:latest
      command: push
  