trigger:
- dev

pool:
  vmImage: 'ubuntu-16.04'

variables:
  version: 0.1.$(Build.BuildId)

name: 0.1.$(BuildId)

steps:
- task: UseDotNet@2
  displayName: 'install dotnet core'
  inputs:
    packageType: sdk
    version: 3.1.201
- script: dotnet tool install -g Microsoft.Tye --version "0.1.0-alpha.20209.5"
  displayName: 'install tye'
- task: NodeTool@0
  displayName: 'Install Node'
  inputs:
    versionSpec: '12.16.1'
- script: npm install
  workingDirectory: DigitalIcebreakers/ClientApp
  displayName: 'Install node dependencies'
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: $(docker-service-connection)
- task: Kubernetes@1
  displayName: kubectl login
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(k8s-service-connection)
    command: login
- task: Docker@2
  displayName: Pull yq
  inputs:
    command: pull
    arguments: osimis/yq

- script: "cat ./DigitalIcebreakers/DigitalIcebreakers.csproj | docker run -i --entrypoint xq osimis/yq -x --arg version $(version) '. * {\"Project\": { \"PropertyGroup\": {Version: $version}}}' | tee ./out.csproj && mv ./out.csproj ./DigitalIcebreakers/DigitalIcebreakers.csproj"
  displayName: update csproj version
- script: "cat ./DigitalIcebreakers/ClientApp/src/version.json | docker run -i --entrypoint jq osimis/yq --arg version $(version) '. * {version: $version}' | tee ./out.json && mv ./out.json ./DigitalIcebreakers/ClientApp/src/version.json"
  displayName: update client app version

- script: tye deploy -v Debug
  displayName: deploy
  