trigger:
- dev

pool:
  vmImage: 'ubuntu-16.04'

variables:
- version: $(Build.BuildNumber)

steps:
# - script: dotnet tool install -g Microsoft.Tye --version "0.1.0-alpha.20209.5"
#   displayName: 'install tye'
# - task: Docker@2
#   displayName: Login to Docker Hub
#   inputs:
#     command: login
#     containerRegistry: $(docker-service-connection)
# - task: Kubernetes@1
#   displayName: kubectl login
#   inputs:
#     connectionType: Kubernetes Service Connection
#     kubernetesServiceEndpoint: $(k8s-service-connection)
- script: cat DigitalIcebreakers/DigitalIcebreakers.csproj | docker run -i --entrypoint xq osimis/yq -x --arg version $(version) '. * {"Project": { "PropertyGroup": {Version: $version}}}' | tee DigitalIcebreakers/DigitalIcebreakers.csproj
  displayName: update version


  
  