# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

resources:
- repo: self

variables:
   # Update Azure.ResourceGroupName value with Azure resource group name.
  Azure.ResourceGroupName: 'digital-icebreakers'

  # Update Azure.ServiceConnectionId value with AzureRm service endpoint.
  Azure.ServiceConnectionId: 'digital-icebreakers-service-connection'

  # Update Azure.Location value with Azure Location.
  Azure.Location: 'australiaeast'

  output: ''

jobs:
- job: DeployVm
  displayName: Deploy VM

  # pool:
  #   vmImage: 'ubuntu-16.04'

  steps:
  - task: AzureResourceGroupDeployment@2
    displayName: Deploy arm template
    inputs:
      azureSubscription: $(Azure.ServiceConnectionId)
      resourceGroupName: $(Azure.ResourceGroupName)
      location: $(Azure.Location)
      templateLocation: deploy.json
      deploymentOutputs: output
